@startuml

class Cliente {
    + Long id
    + String nome
    + String endereco
    + String telefone
    + String email
    + Estado estado
}

class Estado {
    + Long id
    + String nome
    + String pais
}

Cliente "*" --> "1" Estado : pertence a

@enduml